### ISSUE TITLE
when horizontal and more than 1 row, there will be a legible drag and drop.

### ISSUE THREAD

**Issue by charlee2025** [ng-docs/material2#1]
#### Bug, feature request, or proposal:
There are too many elements for drag and drop(horizontal), that one row cannot contain them, so the rest of them will bee  the second row. Then the drag and drop is confused.

#### What is the expected behavior?
when horizontal and more than 1row, there will be a legible drag and drop.

#### What is the current behavior?
the drag and drop is confused.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-furjhv

**Comment by asnowwolf** [comment]
这里是中文文档翻译的问答区，不是关于 material 技术本身的，你可以去 https://github.com/angular/material2/issues 提问。

**Comment by charlee2025** [comment]
好的  感谢  @asnowwolf  关掉这个吧
