### ISSUE TITLE
是否可以让日期控件支持选择日期范围

### ISSUE THREAD

**Issue by 269378737** [ng-docs/material2#9]
#### Please describe the feature you would like to request.
日期控件支持选择日期范围

**Comment by asnowwolf** [comment]
建议到 https://github.com/ng-docs/ng-docs.github.io 提问，这里只是翻译的仓库，平时没有人关注。

**Comment by 269378737** [comment]
> 建议到 https://github.com/ng-docs/ng-docs.github.io 提问，这里只是翻译的仓库，平时没有人关注。

谢谢，上述地址应该是ng的仓库，而不是material ui仓库

**Comment by asnowwolf** [comment]
那里是 ng 所有相关问题的互助组，因为我个人精力有限，所以主要是网友互助。
